language: node_js

dist: xenial

services:
  - xvfb

node_js:
  - 'node'
  - 10
  - 9
  - 8
  - 7
  - 6

before_install:
  - export CHROME_BIN=chromium-browser

cache:
  yarn: true
  directories:
    - node_modules

after_success: codecov
